//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBootstrap.Web.PublishedContentModels
{
	// Mixin content Type 1060 with alias "BehaviorComposition"
	/// <summary>Behavior</summary>
	public partial interface IBehaviorComposition : IPublishedContent
	{
		/// <summary>Internal Redirect</summary>
		IPublishedContent UmbracoInternalRedirectId { get; }

		/// <summary>Hide from menu?</summary>
		bool UmbracoNaviHide { get; }

		/// <summary>Redirect</summary>
		IPublishedContent UmbracoRedirect { get; }

		/// <summary>Url Alias</summary>
		string UmbracoUrlAlias { get; }
	}

	/// <summary>Behavior</summary>
	[PublishedContentModel("BehaviorComposition")]
	public partial class BehaviorComposition : PublishedContentModel, IBehaviorComposition
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "BehaviorComposition";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public BehaviorComposition(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<BehaviorComposition, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Internal Redirect
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent UmbracoInternalRedirectId
		{
			get { return GetUmbracoInternalRedirectId(this); }
		}

		/// <summary>Static getter for Internal Redirect</summary>
		public static IPublishedContent GetUmbracoInternalRedirectId(IBehaviorComposition that) { return that.GetPropertyValue<IPublishedContent>("umbracoInternalRedirectId"); }

		///<summary>
		/// Hide from menu?
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return GetUmbracoNaviHide(this); }
		}

		/// <summary>Static getter for Hide from menu?</summary>
		public static bool GetUmbracoNaviHide(IBehaviorComposition that) { return that.GetPropertyValue<bool>("umbracoNaviHide"); }

		///<summary>
		/// Redirect
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return GetUmbracoRedirect(this); }
		}

		/// <summary>Static getter for Redirect</summary>
		public static IPublishedContent GetUmbracoRedirect(IBehaviorComposition that) { return that.GetPropertyValue<IPublishedContent>("umbracoRedirect"); }

		///<summary>
		/// Url Alias
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return GetUmbracoUrlAlias(this); }
		}

		/// <summary>Static getter for Url Alias</summary>
		public static string GetUmbracoUrlAlias(IBehaviorComposition that) { return that.GetPropertyValue<string>("umbracoUrlAlias"); }
	}
}
