//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBootstrap.Web.PublishedContentModels
{
	// Mixin content Type 1062 with alias "SocialMedia"
	/// <summary>Social Media</summary>
	public partial interface ISocialMedia : IPublishedContent
	{
		/// <summary>Description</summary>
		string OgDescription { get; }

		/// <summary>Images</summary>
		IEnumerable<IPublishedContent> OgImages { get; }

		/// <summary>Title</summary>
		string OgTitle { get; }
	}

	/// <summary>Social Media</summary>
	[PublishedContentModel("SocialMedia")]
	public partial class SocialMedia : PublishedContentModel, ISocialMedia
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SocialMedia";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SocialMedia(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SocialMedia, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("ogDescription")]
		public string OgDescription
		{
			get { return GetOgDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetOgDescription(ISocialMedia that) { return that.GetPropertyValue<string>("ogDescription"); }

		///<summary>
		/// Images
		///</summary>
		[ImplementPropertyType("ogImages")]
		public IEnumerable<IPublishedContent> OgImages
		{
			get { return GetOgImages(this); }
		}

		/// <summary>Static getter for Images</summary>
		public static IEnumerable<IPublishedContent> GetOgImages(ISocialMedia that) { return that.GetPropertyValue<IEnumerable<IPublishedContent>>("ogImages"); }

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("ogTitle")]
		public string OgTitle
		{
			get { return GetOgTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetOgTitle(ISocialMedia that) { return that.GetPropertyValue<string>("ogTitle"); }
	}
}
