//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBootstrap.Web.PublishedContentModels
{
	/// <summary>Grid Page</summary>
	[PublishedContentModel("gridPage")]
	public partial class GridPage : PublishedContentModel, IBehaviorComposition, ISearchEngineOptimization, ISocialMedia
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "gridPage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public GridPage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<GridPage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Layout
		///</summary>
		[ImplementPropertyType("layout")]
		public Newtonsoft.Json.Linq.JToken Layout
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("layout"); }
		}

		///<summary>
		/// Internal Redirect
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent UmbracoInternalRedirectId
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.BehaviorComposition.GetUmbracoInternalRedirectId(this); }
		}

		///<summary>
		/// Hide from menu?
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.BehaviorComposition.GetUmbracoNaviHide(this); }
		}

		///<summary>
		/// Redirect
		///</summary>
		[ImplementPropertyType("umbracoRedirect")]
		public IPublishedContent UmbracoRedirect
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.BehaviorComposition.GetUmbracoRedirect(this); }
		}

		///<summary>
		/// Url Alias
		///</summary>
		[ImplementPropertyType("umbracoUrlAlias")]
		public string UmbracoUrlAlias
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.BehaviorComposition.GetUmbracoUrlAlias(this); }
		}

		///<summary>
		/// Meta Robots Follow
		///</summary>
		[ImplementPropertyType("metaRobotsFollow")]
		public int MetaRobotsFollow
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SearchEngineOptimization.GetMetaRobotsFollow(this); }
		}

		///<summary>
		/// Description: Short description about this page. Should include key word
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SearchEngineOptimization.GetSeoDescription(this); }
		}

		///<summary>
		/// Title: Short title about this page. Should include key word
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SearchEngineOptimization.GetSeoTitle(this); }
		}

		///<summary>
		/// Breadcrumb Title: The title to use in the breadcrumb parts
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SearchEngineOptimization.GetUmbracoUrlName(this); }
		}

		///<summary>
		/// Description
		///</summary>
		[ImplementPropertyType("ogDescription")]
		public string OgDescription
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SocialMedia.GetOgDescription(this); }
		}

		///<summary>
		/// Images
		///</summary>
		[ImplementPropertyType("ogImages")]
		public IEnumerable<IPublishedContent> OgImages
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SocialMedia.GetOgImages(this); }
		}

		///<summary>
		/// Title
		///</summary>
		[ImplementPropertyType("ogTitle")]
		public string OgTitle
		{
			get { return UmbracoBootstrap.Web.PublishedContentModels.SocialMedia.GetOgTitle(this); }
		}
	}
}
