//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBootstrap.Web.PublishedContentModels
{
	// Mixin content Type 1061 with alias "SearchEngineOptimization"
	/// <summary>Search Engine Optimization</summary>
	public partial interface ISearchEngineOptimization : IPublishedContent
	{
		/// <summary>Meta Robots Follow</summary>
		int MetaRobotsFollow { get; }

		/// <summary>Description</summary>
		string SeoDescription { get; }

		/// <summary>Title</summary>
		string SeoTitle { get; }

		/// <summary>Breadcrumb Title</summary>
		string UmbracoUrlName { get; }
	}

	/// <summary>Search Engine Optimization</summary>
	[PublishedContentModel("SearchEngineOptimization")]
	public partial class SearchEngineOptimization : PublishedContentModel, ISearchEngineOptimization
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "SearchEngineOptimization";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public SearchEngineOptimization(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<SearchEngineOptimization, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Meta Robots Follow
		///</summary>
		[ImplementPropertyType("metaRobotsFollow")]
		public int MetaRobotsFollow
		{
			get { return GetMetaRobotsFollow(this); }
		}

		/// <summary>Static getter for Meta Robots Follow</summary>
		public static int GetMetaRobotsFollow(ISearchEngineOptimization that) { return that.GetPropertyValue<int>("metaRobotsFollow"); }

		///<summary>
		/// Description: Short description about this page. Should include key word
		///</summary>
		[ImplementPropertyType("seoDescription")]
		public string SeoDescription
		{
			get { return GetSeoDescription(this); }
		}

		/// <summary>Static getter for Description</summary>
		public static string GetSeoDescription(ISearchEngineOptimization that) { return that.GetPropertyValue<string>("seoDescription"); }

		///<summary>
		/// Title: Short title about this page. Should include key word
		///</summary>
		[ImplementPropertyType("seoTitle")]
		public string SeoTitle
		{
			get { return GetSeoTitle(this); }
		}

		/// <summary>Static getter for Title</summary>
		public static string GetSeoTitle(ISearchEngineOptimization that) { return that.GetPropertyValue<string>("seoTitle"); }

		///<summary>
		/// Breadcrumb Title: The title to use in the breadcrumb parts
		///</summary>
		[ImplementPropertyType("umbracoUrlName")]
		public string UmbracoUrlName
		{
			get { return GetUmbracoUrlName(this); }
		}

		/// <summary>Static getter for Breadcrumb Title</summary>
		public static string GetUmbracoUrlName(ISearchEngineOptimization that) { return that.GetPropertyValue<string>("umbracoUrlName"); }
	}
}
