//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.10.102
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace UmbracoBootstrap.Web.PublishedContentModels
{
	/// <summary>Website</summary>
	[PublishedContentModel("website")]
	public partial class Website : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "website";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Website(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Website, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Cookie Disclairmer
		///</summary>
		[ImplementPropertyType("cookieDisclairmer")]
		public IHtmlString CookieDisclairmer
		{
			get { return this.GetPropertyValue<IHtmlString>("cookieDisclairmer"); }
		}

		///<summary>
		/// Google Analytics Tracking ID: The tracking ID is a string like UA-000000-2. It must be included in your tracking code to tell Analytics which account and property to send data to. Remember to make your Anylytics Account Complaint with GDPR
		///</summary>
		[ImplementPropertyType("gaTrackingID")]
		public string GaTrackingID
		{
			get { return this.GetPropertyValue<string>("gaTrackingID"); }
		}

		///<summary>
		/// Login Page: Select the page where members are able to login.
		///</summary>
		[ImplementPropertyType("loginPage")]
		public IPublishedContent LoginPage
		{
			get { return this.GetPropertyValue<IPublishedContent>("loginPage"); }
		}

		///<summary>
		/// Member Pages: Select the pages which should appear in the authorized menu.
		///</summary>
		[ImplementPropertyType("memberPages")]
		public IEnumerable<IPublishedContent> MemberPages
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("memberPages"); }
		}

		///<summary>
		/// Privacy Policy Page: Select the page which contains privacy policy information.
		///</summary>
		[ImplementPropertyType("privacyPolicyPage")]
		public IPublishedContent PrivacyPolicyPage
		{
			get { return this.GetPropertyValue<IPublishedContent>("privacyPolicyPage"); }
		}

		///<summary>
		/// Register Page: Select the page that handles registration of new members.
		///</summary>
		[ImplementPropertyType("registerPage")]
		public IPublishedContent RegisterPage
		{
			get { return this.GetPropertyValue<IPublishedContent>("registerPage"); }
		}

		///<summary>
		/// Site Name
		///</summary>
		[ImplementPropertyType("siteName")]
		public string SiteName
		{
			get { return this.GetPropertyValue<string>("siteName"); }
		}

		///<summary>
		/// Default Homepage
		///</summary>
		[ImplementPropertyType("umbracoInternalRedirectId")]
		public IPublishedContent UmbracoInternalRedirectId
		{
			get { return this.GetPropertyValue<IPublishedContent>("umbracoInternalRedirectId"); }
		}
	}
}
